# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raw_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eraw_data.proto\"\xa1\x01\n\nSensorData\x12\x14\n\x0cproject_guid\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x61ta_id\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12)\n\x07\x64oubles\x18\x04 \x03(\x0b\x32\x18.SensorData.DoublesEntry\x1a.\n\x0c\x44oublesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raw_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENSORDATA_DOUBLESENTRY._options = None
  _SENSORDATA_DOUBLESENTRY._serialized_options = b'8\001'
  _SENSORDATA._serialized_start=19
  _SENSORDATA._serialized_end=180
  _SENSORDATA_DOUBLESENTRY._serialized_start=134
  _SENSORDATA_DOUBLESENTRY._serialized_end=180
# @@protoc_insertion_point(module_scope)
